# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20171114_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blob',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course'),
        ),
    ]
