# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_chapter', models.PositiveIntegerField()),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_description', models.TextField()),
                ('topic_duration', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Topic',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='topics_course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
