# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20171116_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
