# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20171117_0647'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table='course category',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
