# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20171117_0958'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
    ]
