# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20171125_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=255),
        ),
    ]
