# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='tutor')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tutor',
            },
        ),
    ]
