# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
