# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20171114_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='designation',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(null=True, upload_to='tutor'),
        ),
    ]
