# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0004_auto_20171118_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_student', models.ManyToManyField(related_name='tutor', to='student.Student')),
            ],
            options={
                'verbose_name_plural': 'Tutor Student',
            },
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user_type',
        ),
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
