# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20171119_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='tutor',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='tutor',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
