# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_tutor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorstudent',
            name='tutor_student',
        ),
        migrations.DeleteModel(
            name='TutorStudent',
        ),
    ]
