# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20171125_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='activation_key',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
