# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20171206_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='email_validated',
        ),
    ]
