# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(max_length=200)),
                ('forum_description', models.CharField(max_length=500)),
                ('forum_content', models.TextField()),
                ('created', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Forum',
            },
        ),
    ]
