# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_content', models.TextField()),
                ('created', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Forum Thread',
            },
        ),
        migrations.RemoveField(
            model_name='forum',
            name='created',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='forum_content',
        ),
        migrations.AddField(
            model_name='forumthread',
            name='forum_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Forum'),
        ),
    ]
