# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student Assigned'),
        ),
    ]
