# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20171125_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default=0, upload_to='student'),
            preserve_default=False,
        ),
    ]
