# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20171125_2031'),
        ('student', '0008_auto_20171127_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='my_course',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='my_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
