# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20171127_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='my_course',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
