# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20171128_0343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_auto_20171129_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_course', models.ManyToManyField(to='course.Course')),
            ],
            options={
                'verbose_name_plural': 'Student Courses',
            },
        ),
    ]
