# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20171125_2031'),
        ('student', '0010_auto_20171127_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='my_course',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='my_course',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
