# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20171206_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
