# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20171206_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=4, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default=5, upload_to='student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default=6, max_length=200),
            preserve_default=False,
        ),
    ]
